global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: servidor
    static_configs:
      - targets: 
        - 172.18.160.1:9182  # Substitua pelo endereço IP ou nome do servidor onde o Node Exporter está em execução.
        - 10.10.10.5:9182